version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Use .env file instead of hardcoding
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent database storage

  backend:
    build: ./backend  # Now correctly points to backend/
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: lms_db
    env_file:
      - .env  # Move sensitive data here

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pg_data:  # Persistent volume for database storage
