pipeline {
    agent any
    environment {
        REPO_URL = 'https://github.com/Chandrashekar-07/LMS-Project.git'
        DOCKER_IMAGE = 'lms_project'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }
        stage('Build') {
            steps {
                sh '''
                docker-compose down || true
                docker-compose build
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose run backend pytest || true'
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                docker-compose down || true
                docker-compose up -d
                '''
            }
        }
    }
    post {
        success {
            echo "Deployment Successful! 🎉"
        }
        failure {
            echo "Pipeline Failed! ❌"
        }
    }
}
